=== mibig-secmet/schema/schemas/mite/entry.json
{
  "$id": "https://meta.secondarymetabolites.org/schemas/mite/entry.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Minimum Information about a Tailoring Enzyme/Maturase Data Standard",
  "additionalProperties": false,
  "properties": {
    "accession": {
      "title": "MITE accession number/identifier.",
      "$ref": "#/$defs/entryId"
    },
    "changelog": {
      "title": "Log tracking changes in entry.",
      "$ref": "/schemas/common/changelog.json"
    },
    "quality": {
      "title": "Track quality of entry.",
      "$ref": "#/$defs/quality"
    },
    "status": {
      "title": "Track status of entry.",
      "$ref": "#/$defs/status"
    },
    "enzyme": {
      "title": "(Meta)data about the enzyme described by entry.",
      "$ref": "/schemas/mite/enzyme.json"
    },
    "compounds": {
      "type": "array",
      "title": "Mature compound(s) associated with enzyme (were acted on by enzyme).",
      "items": {
        "$ref": "/schemas/mite/compounds.json"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "genomic_context": {
      "title": "(Meta)data on genomic context of the enzyme (associated biosynthetic gene cluster).",
      "$ref": "/schemas/mite/genomic_context.json"
    },
    "reactions": {
      "title": "One or more reaction patterns of enzyme.",
      "type": "array",
      "items": {
        "$ref": "/schemas/mite/reactions.json"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "comment": {
      "title": "Any additional information about this entry",
      "type": "string"
    }
  },
  "$defs": {
    "entryId": {
      "type": "string",
      "pattern": "^MITE\\d{7,7}$"
    },
    "quality": {
      "type": "string",
      "enum": ["questionable", "low", "medium", "high"]
    },
    "status": {
      "type": "string",
      "enum": ["pending", "embargoed", "active", "retired"]
    }
  },
  "required": [
    "accession",
    "changelog",
    "quality",
    "status",
    "compounds",
    "genomic_context",
    "reactions"
  ]
}

=== mibig-secmet/schema/examples/mite/entry/mcjC.json
{
  "accession": "MITE0000001",
  "changelog": {
    "releases": [
    {
      "version": "next",
      "date": "2024-02-20",
      "entries": [
        {
          "contributors": ["AAAAAAAAAAAAAAAAAAAAAAAA"],
          "reviewers": ["BBBBBBBBBBBBBBBBBBBBBBBB"],
          "date": "2024-02-20",
          "comment": "Initial entry."
        }
      ]
    }
  ]
  },
  "quality": "high",
  "status": "pending",
  "enzyme": {
    "name": "McjC",
    "description": "Lassopeptide ATP-dependent lactam synthetase (C-protein, asparagine synthetase-like)",
    "databaseIds": [
      "uniprot:Q9X2V9",
      "genpept:AAD28496.1"
    ],
    "auxiliary_enzymes": [
      {
        "name": "McjB",
        "description": "Lassopeptide cysteine protease. Required for macrolactam-synthethase function (folds and cleaves precursor peptide)",
        "databaseIds": [
          "uniprot:Q9X2V8",
          "genpept:AAD28495.1"
        ]
      }
    ],
    "references": [
      "doi:10.1128/jb.181.8.2659-2662.1999",
      "doi:10.1002/cbic.201200016"
    ]
  },
  "compounds": [
    {
      "name": "microcin J25",
      "classes": [
        "peptide"
      ],
      "structure": "CC[C@H](C)[C@H](NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@@H]1CCC(=O)NCC(=O)NCC(=O)N[C@@H](C)C(=O)NCC(=O)N[C@@H](Cc2c[nH]cn2)C(=O)N[C@@H](C(C)C)C(=O)N2CCC[C@H]2C(=O)N1)C(C)C)C(=O)NCC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NCC(=O)O)[C@@H](C)CC)[C@@H](C)O",
      "databaseIds": [
        "npatlas:NPA05946"
      ],
      "evidence": [
        {
          "method": [
            "Mass spectrometry",
            "MS/MS",
            "NMR",
            "Total synthesis"
          ],
          "references": [
            "doi:10.1021/ja036756q"
          ]
        }
      ]
    }
  ],
  "genomic_context": {
    "classes": [
      "Ribosomal"
    ],
    "accession_genome": {
      "accessionID": "AF061787.1"
    },
    "taxonomy": {
      "name": "Escherichia coli AY25",
      "ncbiTaxId": 562
    },
    "databaseIds": [
      "mibig:BGC0000581"
    ],
    "evidence": [
      {
        "evidenceCode": [
          "Knock-out studies"
        ],
        "references": [
          "doi:10.1128/jb.181.8.2659-2662.1999"
        ]
      }
    ]
  },
  "reactions": [
    {
      "tailoring": [
        {
          "function": "Macrolactam formation"
        }
      ],
      "description": "Lassopeptide macrolactam formation after N-terminal cleavage: NH2-G-G-X-X-X-X-X-D/E-Xn-COOH.",
      "reactionSMARTS": {
        "reactionSMARTS": "([#7:1]-[#6:2]-[#6:3](=[O:4])-[#7:5]-[#6:6]-[#6:7](=[O:8])-[#7:9]-[#6:10]-[#6:11](=[O:12])-[#7:13]-[#6:14]-[#6:15](=[O:16])-[#7:17]-[#6:18]-[#6:19](=[O:20])-[#7:21]-[#6:22]-[#6:23](=[O:24])-[#7:25]-[#6:26]-[#6:27](=[O:28])-[#7:29]-[#6:30](-[#6:31]-[#6:32](-[#8:35])=[O:36])-[#6:33]=[O:34])>>([O:34]=[#6:33]-[#6:30]-1-[#6:31]-[#6:32](=[O:36])-[#7:1]-[#6:2]-[#6:3](=[O:4])-[#7:5]-[#6:6]-[#6:7](=[O:8])-[#7:9]-[#6:10]-[#6:11](=[O:12])-[#7:13]-[#6:14]-[#6:15](=[O:16])-[#7:17]-[#6:18]-[#6:19](=[O:20])-[#7:21]-[#6:22]-[#6:23](=[O:24])-[#7:25]-[#6:26]-[#6:27](=[O:28])-[#7:29]-1) |Sg:n:30:1-2:ht,Sg:n:39:1-2:ht|",
        "isIterative": false,
        "hasLinker": true,
        "hasPositionVariationBond": false,
        "explicitHydrogen": [
          {
            "index": 1,
            "nrHydrogens": 2
          },
          {
            "index": 2,
            "nrHydrogens": 2
          },
          {
            "index": 6,
            "nrHydrogens": 2
          }
        ],
        "evidence": [
          {
            "evidenceCode": [
              "Heterologous expression",
              "Site-directed mutagenesis"
            ],
            "references": [
              "doi:10.1074/jbc.M803995200"
            ]
          }
        ]
      },
      "validated_reactions": [
        {
          "substrate_(sub)structure": "CC[C@H](C)[C@H](NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@H](CCC(=O)O)NC(=O)[C@@H]1CCCN1C(=O)[C@@H](NC(=O)[C@H](Cc1c[nH]cn1)NC(=O)CNC(=O)[C@H](C)NC(=O)CNC(=O)CN)C(C)C)C(C)C)C(=O)NCC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NCC(=O)O)[C@@H](C)CC)[C@@H](C)O",
          "product_(sub)structure": [
            "CC[C@H](C)[C@H](NC(=O)CNC(=O)[C@@H](NC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O)[C@@H]1CCC(=O)NCC(=O)NCC(=O)N[C@@H](C)C(=O)NCC(=O)N[C@@H](Cc2c[nH]cn2)C(=O)N[C@@H](C(C)C)C(=O)N2CCC[C@H]2C(=O)N1)C(C)C)C(=O)NCC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NCC(=O)O)[C@@H](C)CC)[C@@H](C)O.O"
          ],
          "isBalanced": true,
          "isAuthentic": true,
          "isIntermediate": false,
          "description": "Lasso macrocyclisation of microcin J25 after precursor cleavage, leading to mature product.",
          "evidence": [
            {
              "evidenceCode": [
                "Heterologous expression",
                "Site-directed mutagenesis"
              ],
              "references": [
                "doi:10.1074/jbc.M803995200"
              ]
            }
          ]
        }
      ]
    }
  ],
  "comment": "Lasso peptide macrolactam (lariat-fold) introducing lactam synthase (C-protein) from Escherichia coli AY25"
}
