=== mibig-secmet/schema/schemas/mibig/biosynthesis/domains/acyltransferase.json
{
  "$id": "https://meta.secondarymetabolites.org/schemas/mibig/biosynthesis/domains/acyltransferase.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "type": {
      "const": "acyltransferase"
    },
    "subtype": {
      "type": "string",
      "enum": ["cis-AT", "trans-AT"]
    },
    "gene": {
      "$ref": "/schemas/common/gene_id.json"
    },
    "location": {
      "$ref": "/schemas/common/location.json"
    },
    "inactive": {
      "type": "boolean"
    },
    "substrates": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/substrate"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "evidence": {
      "type": "array",
      "items": {
        "$ref": "/schemas/mibig/common/substrate_evidence.json"
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": ["type", "gene", "location"],
  "$defs": {
    "substrate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "enum": [
            "malonyl-CoA",
            "methylmalonyl-CoA",
            "ethylmalonyl-CoA",
            "other"
          ]
        },
        "details": {
          "type": "string"
        },
        "structure": {
          "$ref": "/schemas/common/smiles.json"
        }
      },
      "required": ["name"]
    }
  }
}

=== mibig-secmet/schema/examples/mibig/biosynthesis/modules/domains/acyltransferase/trans_at.json
{
  "type": "acyltransferase",
  "subtype": "trans-AT",
  "gene": "ABS74182.1",
  "location": {
    "from": 6,
    "to": 290
  },
  "substrates": [
    {
      "name": "malonyl-CoA"
    }
  ],
  "evidence": [
    {
      "name": "Structure-based inference",
      "references": ["pubmed:12345"]
    }
  ]
}
